### ISSUE TITLE
ARDUndZDF not compatible with this version of Kodi

### ISSUE THREAD

**Issue by Nears** [rols1/Kodi-Addon-ARDundZDF#1]
Today I got an automated update of the Addon based on the Kodi-Nerds Repo I am using.
Now i have the latest version 2.8.3 of the add-on installed in the my kodi Kodi 18.6 and I receive the following error:

"ARDUndZDF: The add-on is not compatible with this version of Kodi"

I am not able to enable the add-on any longer.

Kodi Log says:
ERROR: Add-on 'plugin.video.ardundzdf' is not compatible with Kodi
ERROR: CAddonInstallJob[plugin.video.ardundzdf]: failed to reload addon
ERROR: Add-on 'plugin.video.ardundzdf' is not compatible with Kodi

Please let me know what additional information you need to fix this problem.

Sorry for crosspost. See also here: https://www.kodinerds.net/index.php/Thread/64244-RELEASE-Kodi-Addon-ARDundZDF/?pageNo=51#post583293 (German)

**Comment by rols1** [comment]
an initial testversion for Kodi-Matrix you can get there: [plugin.video.ardundzdf-x.x.x+matrix.zip](https://c.gmx.net/@327723216099344844/cASZJUNuQpqlEImIS62dmA)<br>
The intern update-modul allows to get the following updates from the github-repo here.
Or you can use the kodinerds-repo to choose between leia-/krypton- or matrix-version.
/R
