### ISSUE TITLE
LiveTV: ZDFinfo statt ZDF

### ISSUE THREAD

**Issue by pp0815** [rols1/Kodi-Addon-ARDundZDF#10]
Hallo und guten Tag,

auf einem (aktuellen) Android-Tablet (Kodi Matrix) erscheint seit ein paar Tagen bei LiveTV der Sender ZDFinfo statt ZDF, - obwohl EPG die Daten von ZDF in der Übersicht richtig voranzeigt. De- und Reinstallation des Addons hat nicht geholfen. Es wurde auch "Links werden erneuert" eingeblendet; also alles wie üblich. 

Gleiches Fehlverhalten tritt übrigens auch bei einer komplett frischen Installation von Kodi (Matrix) und Addon auf einem LineageOS-Gerät auf.

Repo: kodinerds

Bei meinen älteren Kodi/Leia-Clienten funktioniert hingegen alles wie gewünscht.

Was kann das sein und wie bekommt man es weg?

Danke und viele Grüße, pp0815

**Comment by rols1** [comment]
Hallo pp0815,
im letzten Update wurden die Cache-Funktionen an ARD- und ZDF-Änderungen angepasst. Da dürfte der Fehler liegen. Fix folgt voraussichtl. morgen - wie unter der Woche üblich im Testaddon auf gmx (siehe [Startpost im  kodinerds-Forum](https://www.kodinerds.net/index.php/Thread/64244-RELEASE-Kodi-Addon-ARDundZDF/?pageNo=1#post502022).
Gruß
/R

**Comment by rols1** [comment]
nach Einblick in den Code schon gefixt (weniger Aufwand als vermutet). Für den Sender phoenix war ein zusätzl. Fix erforderlich. Um phoenix vor Erneuerung des Caches (12 Std. Haltezeit) zu sehen,  ist im Cache-Verzeichnis, Unterverz. Dict (s. Menü "Info" / "Addon-Infos") die Datei zdf_streamlinks zu entfernen.
/R

**Comment by pp0815** [comment]
Wow, das ging schnell. Vielen vielen Dank, auch generell für die Arbeit am Addon :-)
