### ISSUE TITLE
support for python3

### ISSUE THREAD

**Issue by foss-** [rols1/Kodi-Addon-ARDundZDF#13]
When trying to install version 4.3.0 of the add-on from zip, Kodi 19.4 complains about `The dependent xbmc.python version 2.25.0 could not be satisfied.`

**Comment by rols1** [comment]
for the first installation on Kodi-Matrix you need  the matrix-version of this addon - download here: [kodinerds-Repo, choose  Kodi 19 in tab Kodi-Version](https://repo.kodinerds.net). The code basis is identical.
If you can read german, you find some more infos in README and a lot more infos in [Wiki](https://github.com/rols1/Kodi-Addon-ARDundZDF/wiki).
If you want to track discussions and development please look at [Forum Kodinerds](https://www.kodinerds.net/index.php/Thread/64244-RELEASE-Kodi-Addon-ARDundZDF)
/R

**Comment by foss-** [comment]
That worked, thanks for pointing into the right direction and sorry for not reading the readme properly.
