### ISSUE TITLE
Incompatible with current Kodi Versions

### ISSUE THREAD

**Issue by JulianOestreich90** [rols1/Kodi-Addon-ARDundZDF#14]
Can you make your Code compatible with up-to-date Python Versions? Unfortunatly your Addon is using Python 2, which is dead and incompatible with current Kodi Versions.

**Comment by rols1** [comment]
for the first installation on Kodi-Matrix you need  the matrix-version of this addon - download here: [kodinerds-Repo, choose  Kodi 19 in tab Kodi-Version](https://repo.kodinerds.net). The code basis is identical.
If you can read german, you find some more infos in README and a lot more infos in [Wiki](https://github.com/rols1/Kodi-Addon-ARDundZDF/wiki).
If you want to track discussions and development please look at [Forum Kodinerds](https://www.kodinerds.net/index.php/Thread/64244-RELEASE-Kodi-Addon-ARDundZDF)

I will switch the Release-ZIP bit Matrix if a few month. There are still a lot of Leia installations.
/R
