### ISSUE TITLE
Adding the addon to the default repos and replacing the other media-library addons with it

### ISSUE THREAD

**Issue by mYnDstrEAm** [rols1/Kodi-Addon-ARDundZDF#15]
This is the best Kodi add-on for German-language public media and the ones in the Kodi repositories are far less usable, less convenient, have more bugs and often don't work at all.

It would be very useful if it was added to the default Kodi repos so people can easily find it *and* don't install less-functional add-ons instead.

Then the media library addons currently in there should get removed for these reasons (ARD Mediathek, ZDF Mediathek, 3sat Mediathek, etc). They should also be removed from https://kodi.tv/addons/matrix/category/video-addons (edit: and from [here](https://www.kodi-tipps.de/ard-mediathek-kodi-addon-installieren/) & [here](https://kodi.wiki/view/Add-on:Mediathek) for example, or at least a note should be added). The description for the ARDundZDF should however get changed so that people know which channels are supported and can find it in searches (mainly within Kodi). Related issue: https://github.com/sarbes/script.module.libzdf/issues/4

It should also be in the repos of the Kodi version in Debian stable (11) which is v19.1 (Matrix). Having it in the repos there prevents problems with version mismatches and allows easy installation. The addon version that works with it is the latest code .zip file (v4.3.4+matrix).

Moreover, it would be good if this addon was recommended to users if the configured language is German (but this is a separate issue and more an issue of Kodi to enable addon-recommendations [via popup and based on settings] within Kodi).

Thanks for reenabling Issues in this repo and for helping out in the forums: it can be installed in Debian11 when the .zip file of the source is installed instead of the version from the releases (sha256sum is `00f2b49321174b6d169ba149c3ac1fa902a7d9cdb7cecbe6a9c86e2176521aad`).

**Comment by rols1** [comment]
Vorweg: danke für das Lob. Dabei gehört ein wesentlicher Anteil den Nutzern bei kodinerds, die mit Anregungen zur Weiterentwicklung beigetragen haben. Der damit erreichte akt. Stand geht m.E.  weit über die ursprüngliche Plexversion hinaus.

> Thanks for reenabling Issues in this repo and for helping out in the forums: it can be installed in Debian11 when the .zip file of the source is installed instead of the version from the releases (sha256sum is `00f2b49321174b6d169ba149c3ac1fa902a7d9cdb7cecbe6a9c86e2176521aad`)

danke für den Hinweis. Da in den letzten Wochen der Abruf der Matrix-Version stark zugenommen hat, stelle ich voraussichtlich zum nächsten Update auch das Release-ZIP auf Matrix um. Dabei handelt es sich lediglich um kleine Anpassungen in der Datei addon.xml (Versionsbez. für Addon und Python); die Codebasis ist identisch. Die meisten Neuinstallationen dürften auf Kodi-Matrix erfolgen und nur noch wenige auf Leia/Krypton. 
Am liebsten ist mir, wenn die Nutzer bei beiden Versionen auf das kodinerds-Repo oder dessen Webversion https://repo.kodinerds.net zugreifen. Github ist zwar super für Entwickler, für normal Nutzer jedoch ziemlich sperrig.

> It would be very useful if it was added to the default Kodi repos so people can easily find it _and_ don't install less-functional add-ons instead. ff..

das strebe ich nicht an. Im Gegensatz zum international verwendeten Addon TuneIn2017 sehe ich die Heimat von ARDundZDF wegen des deutsprachigen Bezugs bei kodinerds und nicht beim Kodi Community Forum. Ich schätze bei kodinerds - wie bereits erwähnt - den fruchtbaren Dialog sowie auch die gute Moderation. 
Keine Einwände hätte ich gegen einen Querverweis mit dem Hinweis auf den Support bei kodinerds. Einen zusätzl. Support-Thread für das Addon bei forum.kodi.tv kann (und will) ich mir zeitlich nicht leisten. 

> Then the media library addons currently in there should get removed for these reasons (ARD Mediathek, ZDF Mediathek, 3sat Mediathek, etc). They should also be removed from https://kodi.tv/addons/matrix/category/video-addons. The description for the ARDundZDF should however get changed so that people know which channels are supported and can find it in searches (mainly within Kodi). Related issue: [sarbes/script.module.libzdf#4](https://github.com/sarbes/script.module.libzdf/issues/4)

hierzu möchte ich auf die beiden Entwickler 68000a (Repo Gigathek) und [realvito  mit seinem Fixing thread](https://www.kodinerds.net/index.php/Thread/55451-L0REs-Blog-realvitos-Fixing-Thread/)  bei kodinerds hinweisen, welche die angesprochenen Mediatheken weiter pflegen. Persönlich sehe ich hier keine Konkurrenz, sondern hilfreiche Vielfalt.

Ich versuche mal, meine Einstellung zu den issues #15,#16,#17 zusammenzufassen:

- Aufnahme in das default kodi repo unterstütze ich nicht, wohl aber einen entspr. Hinweis auf das Addon und den Support bei kodinerds
- Ähnliches gilt für die Anregung zum Entfernen nicht funktionierender Mediatheken: Hinweis auf Support bei kodinerds durch andere Entwickler. Vorstellbar wäre auch die Entfernung der Mediatheken, falls die ursprünglichen Entwickler nicht weiter Support leisten können
- zu Streamqualität und Streamkontrolle: hier sehe ich wenig Möglichkeiten zur Verbesserung im Addon (auf die beeinflussenden Faktoren bin ich eingegangen). Ev. wäre der vorgeschlagene Dialog "Set this as default view-setting?" hilfreich für einige Nutzer. Das würde ich in Angriff nehmen, falls noch mehr Nutzer so etwas wünschen
- Transfer Merkliste zu Kodi's movies page: sehe ich auch vorrangig als Kodi-Thema. Im Moment gibt es  tatsächlich die Trennung zwischen Mediatheks-Inhalten und den Verzeichnissen, die vom Nutzer für die Kodi-Bibliothek freigegeben sind und von Kodi (einschl. genutzten Scrapern) gescannt werden. Im Addon gibt es mit den strm-Dateien und den strm-Verzeichnissen immerhin einen Weg von der Mediathek zu einem Bibliotheks-Verzeichnis. In dieser Richtung könnte man weiter entwickeln. Ein Problem sehe ich in den unterschiedlichen Genre-Zuordnungen bei den Sendern. 
- die vorgeschlagene Übergangslösung für Dokumentarfilme muss ich mir nochmal ansehen (habe ich noch nicht verstanden)

/R

**Comment by mYnDstrEAm** [comment]
>Da in den letzten Wochen der Abruf der Matrix-Version stark zugenommen hat, stelle ich voraussichtlich zum nächsten Update auch das Release-ZIP auf Matrix um

Klingt gut.

>das strebe ich nicht an. Im Gegensatz zum international verwendeten Addon TuneIn2017 sehe ich die Heimat von ARDundZDF wegen des deutsprachigen Bezugs bei kodinerds und nicht beim Kodi Community Forum. Ich schätze bei kodinerds - wie bereits erwähnt - den fruchtbaren Dialog sowie auch die gute Moderation.

Das macht Sinn, war aber nicht das, was ich gemeint habe: mir geht es nur darum, dass das Addon direkt in der default vanilla Kodi-Installation verfügbar ist wenn man innerhalb von Kodi unter der Seite "Addons" sucht oder durch die verfügbaren Addons scrollt. Die Addons ARD Mediathek und ZDF Mediathek sind dort bereits: diese sollten entfernt und dein Addon hinzugefügt werden. Der Thread würde ja bei kodinerds bleiben.

> welche die angesprochenen Mediatheken weiter pflegen. Persönlich sehe ich hier keine Konkurrenz, sondern hilfreiche Vielfalt.

Vielleicht hat das tatsächlich genügend Vorteile...bei mir hatten die Addons aber viele Fehler so dass sie kaum benutzbar sind. Woher soll der Nutzer denn wissen welche Addons wie gut funktioniert und wie nutzerfreundlich und convenient sie sind? Ein Mediathek-Addon das viele verschiedene Mediatheken vereint scheint mir auch ganz prinzipiell überlegen. Es würde Sinn machen mehr bzw. den Fokus der Entwicklerarbeit auf das unified und besser-funktionierende Addon zu legen. Man kann ja durch Bugfixes aufgrund von breaking changes immer noch gewährleisten, dass die Addons bestehen bleiben und es noch einen Grad an Vielfalt gibt. Ansonsten ist dein Addon ja open source so dass man es falls angebracht einfach forken könnte. Insofern sehe ich hier in der Praxis eigentlich nur Nachteile und sehe das auch gar nicht als Konkurrenz, sondern als Ineffizienz und Verringerung der Convenience von Kodi.

> Aufnahme in das default kodi repo unterstütze ich nicht

Bis jetzt hast du aber nur das mit dem Forumthread begründet, das Addon könnte doch auch ohne diesen hinzugefügt werden.

>zu Streamqualität und Streamkontrolle[...] Das würde ich in Angriff nehmen, falls noch mehr Nutzer so etwas wünschen

Das wichtige war, dass der Stream per Default mit nur einem Klick startet ohne dass man erst noch die Einstellungen kennen, finden und ändern muss. Das mit der Streamqualität ist da eher zweitrangig, da wird man auch eher in den Einstellungen nachschauen (und es schnell finden), ich werde das mal testen/nutzen und schauen, wie nützlich solche Features wären und das evtl im Thread ansprechen je nachdem ob es momentan noch wichtigere Issues gibt. Kann mir gut vorstellen, dass andere Nutzer das auch gut finden würden.

>Transfer Merkliste zu Kodi's movies page: sehe ich auch vorrangig als Kodi-Thema.

Werde ich mir wann anders genauer anschauen und dann ein Thread im Kodi Forum dazu machen. Das kann nicht umgesetzt werden, solange die entsprechenden Kodi-Änderungen nicht implementiert wurden. Danke für die Infos zu den strm Datein und den Grenre Tags.

>die vorgeschlagene Übergangslösung für Dokumentarfilme muss ich mir nochmal ansehen (habe ich noch nicht verstanden)

Das ist nur die Übergangslösung für eine Trennung zwischen Dokus und Filmen in Kodi: man kann zwei Einträge unter Favoriten erstellen: einen für die Filme-Seite mit Genre:Dokumentation rausgefiltert und einen für die Filme-Seite mit allem außer Genre:Dokumentation rausgefiltert. Es ist also keine Übergangslösung für das Hinzufügen von Einträgen in der Merkliste zu Kodi's Filme-Seite.

**Comment by rols1** [comment]
> Bis jetzt hast du aber nur das mit dem Forumthread begründet, das Addon könnte doch auch ohne diesen hinzugefügt werden.

stimmt -zugegeben. Aber das reguläre Hinzufügen ist mit Aufwand verbunden, nämlich mit Pull-Requests zum  [Official add-on repository[(https://kodi.wiki/view/Official_add-on_repository). Außerdem sind vermutlich noch Detailanpassungen im Addon erforderlich um Konformitätsanforderungen zu entsprechen. Um ehrlich zu sein: ich möchte mir einfach keinen weiteren organisatorischen Aufwand aufhalsen. Die Webseiten der Mediatheken werden dynamisch entwickelt - entsprechend ist der zeitliche Aufwand für Anpassungen (die Audiothek der ARD hat z.B. zwei komplette Renovierungen hinter sich).
Wie du aber richtig angemerkt hast, ist jederzeit ein Fork möglich, so dass dieser Aufwand von Dritten geleistet werden könnte - diese sollten aber wegen des Baustellencharakters des Addon-Codes schmerzfrei sein  
/R

**Comment by rols1** [comment]
> Wenn du das momentan nicht umsetzen möchtest, stößt vielleicht jemand anders auf dieses Issue und entwickelt die entsprechenden Pull Requests

ganz in meinem Sinne und Hilfestellung würde ich nicht verweigern. 

> : eben _weil_ das Addon so viel Arbeit gekostet hat (und womöglich weiterhin kostet) möchte man doch, dass es auch genutzt wird oder nicht?

sicher, und bei aller Freude über Anregungen und positiven Rückmeldungen: es gibt auch eine Eigenverantwortung für die Lebensbalance. Für mich stehen die realen sozialen Kontakte im Vordergrund; das Addon-Hobby darf dabei nicht zum Verdränger werden. Vielleicht hängt es auch mit meinem Lebensalter zusammen - da freut man sich über bewegliche Gelenke mehr als über eine Ausweitung der Nutzergemeinde.
/R

**Comment by rols1** [comment]
ich würde den issue gerne schließen, falls sich keiner meldet, der die Kerner-Arbeit (Hinzufügen zum Official add-on repository) übernimmt. Zieldatum 01.06.2022 - einverstanden?

**Comment by rols1** [comment]
OK  - neues Zieldatum 01.06.2022 zum Offenhalten: 01.07.2022.
In den 7 Wochen sollte deutlich werden, ob sich deine Anregung vollzieht - in welcher Form auch immer.
Und: letzlich ist anzuerkennen, wenn eine Intiative wegen abweichender Motivation nicht auf fruchtbaren Boden fällt.
/R

**Comment by mYnDstrEAm** [comment]
Bin das jetzt durchgegangen: du müsstest einfach nur diesen Pull Request erstellen, mehr ist das nicht: https://kodi.wiki/view/Submitting_Add-ons#Pull_requests

Ich kann das nicht tun, da "You acknowledge that you are the maintainer of your add-on" eines der [Add-on rules](https://kodi.wiki/view/Add-on_rules) ist, die ansonsten alle erfüllt werden...wobei ich Punkt 3 nicht durchgegangen bin, die "General requirements" wie insbesondere "all strings used by add-ons must be localized, no hard-coded language strings should ever be used" (kann man auch [hiermit](https://pypi.org/project/kodi-addon-checker/) überprüfen).

Motivation, Nützlichkeit, Befürwortung, K/N-Effizienz, etc sind hier alle vorhanden, man müsste zumindest erst mal den Pull-Request erstellen und viel mehr als das wird es nicht sein. Die Commit Message wäre denke ich "[plugin.video.ardundzdf] 4.4.0" und das Repo https://github.com/xbmc/repo-plugins/tree/matrix ([pulls](https://github.com/xbmc/repo-plugins/pulls))

**Comment by rols1** [comment]
Umsetzung für mich zur Zeit zu aufwändig. 
/R
