### ISSUE TITLE
Adding items from the Merkliste/watch-list to Kodi's movies page

### ISSUE THREAD

**Issue by mYnDstrEAm** [rols1/Kodi-Addon-ARDundZDF#17]
This is (at least currently/mostly) an issue of Kodi and you could close it.

Here we could discuss how this could be done, how interfacing Addon<->Kodi's Movies page (as well as the Series page and a Documentaries page that I [proposed in the forums](https://forum.kodi.tv/showthread.php?tid=362894)) could be done. It would also need various changes to the addon once it's possible in Kodi (like somehow setting genre tags for items in the media library).

It would be best and most useful and convenient if the addon showed media from the library alongside items from other addons and local files on the hard drive unified in the Movies/Series/Documentaries pages. This would make Kodi _the ultimate media library_/Mediathek...currently you need to decide if you'll **either** watch something from the media libraries in the addon **or** something else you added to the Kodi media center.

I think it would be best if one could configure the addon to automatically add all items in the Merkliste/watch-list to your Kodi pages. They would get removed from there once the media is no longer available for time-restricted items. It's important that items have the correct genre tag set (and I don't think that this info is currently retrieved by the scraper) so that for example documentaries don't clutter your fictional movies page but show up under your Documentaries view*. This also applies for series and I suggest that news broadcasts are added to Documentaries while series of fiction and and informative series of reports are added to Series.

*a current workaround until Kodi adds a separate Documentaries page is to add a filtered Movies view to your Favorites that filters out items of genre Documentary and another filtered movies view that only shows items with genre Documentary

**Comment by rols1** [comment]
> It would also need various changes to the addon once it's possible in Kodi (like somehow setting genre tags for items in the media library).
exactly, it depends..
I would be willing to implement your suggestions in the addon if the conditions change. Honestly, I'm skeptical that the German broadcasters will find a common standard for the required designations.

btw: I dont' use Kodi's library myself. When I implemented the strm-Modul (january 2022, V4.1.9) I had to learn a lot about the relevant Kodi features. And I must learn, that it isn't possible  (at this time) to assign the videos to a  specific genre. Even in the case of a single broadcaster (ZDF) there are different marking at series.

**Comment by mYnDstrEAm** [comment]
Great!

I don't think this depends on the broadcasters. There's many ways this could be solved such as people creating imdb entries for all their media or setting the genre tags depending on where the media is located in their media library (for example they often have a separate category for fictional series or for a specific documentary series etc). Another approach would be to set "documentary" (or a new genre) as a default genre and then allow Kodi users to become librarians that can easily edit the metainfo like the genres of items from within Kod. Maybe somebody else has more ideas how this problem could be solved. In that case, please post it here.

Why is it currently impossible to assign the videos to a specific genre? I guess the needed field for genre could be added to the xml/json file once it's possible to integrate films from addons into Kodi's library pages. Are you referring to different markings in the response of their API? If so they could get standardized from the request side.

**Comment by rols1** [comment]
> Are you referring to different markings in the response of their API? If so they could get standardized from the request side.

that is precisely the problem. 
In the addon, I essentially evaluate the html source text (ZDF, 3sat, phoenix), in some cases the answers in json format (new ARD), in other cases the json area attached to the html code (e.g. Arte). 
Unfortunately, there is a lack of uniform labelling in the various mediatheques. This is the reason why the addon can so far only create strm files for some ZDF and ARD series. 
The same applies to the documentaries you mentioned. These, too, are labelled differently by ARD, ZDF, Arte, etc. In some cases, a "Partnersender" uses different labels than the original broadcaster when repeating a show (e.g. phoenix for a show from zdf-Info). 
/R

**Comment by rols1** [comment]
Deine Threads im Kodi-Forum zu den Themen [support documentaries and short films by default](https://forum.kodi.tv/showthread.php?tid=362894&highlight=Documentaries)und [Feature Requests für den Estuary-Skin](https://forum.kodi.tv/showthread.php?tid=262603) habe ich mir angesehen und verstehe dein Anliegen jetzt besser.
Egal ob eine entsprechene Änderung im Core von Kodi oder eine Anpassung des Default-Skin Estuary kommt (nach meiner Einschätzung kommt beides nicht), bleibt das oben diskutierte Problem mit den unterschiedlichen Bezeichnungen in den Mediatheken. 
Letzteres ist für das Addon relevant. Deshalb gibt es in der Merkliste die Option zum nachträglichen Umbenennen. Ich weiß: nur ein schwacher Trost, aber dein Anliegen wird vermutlich nur durch zusätzliche eigene Konfiguration möglich sein (wie z.B. mit dem Playlist-Vorschlag vom Kodi-Member the_other_guy).

Wie machen wir hier weiter - schließen wie eingangs freigestellt oder offenlassen für weitere Beiträge?

**Comment by mYnDstrEAm** [comment]
Ich bin ganz klar und sehr für ein Offenlassen, das Issue hängt ja von Änderungen in Kodi ab. Sobald und falls die umgesetzt werden könnte man das im Addon umsetzen. Vielleicht liest das ja ein Kodi-Dev und setzt das dann um oder findet hier relevante Infos oder ein Nutzer möchte mit einem Subscribe auf dem aktuellen Stand diesbezüglich bleiben oder von anderer Stelle (wie dem Kodi-Forum oder einem Issue in einem anderen Repo) hierher verlinken.

**Comment by rols1** [comment]
keine weiteren Beiträge seit mehr als 6 Wochen. Wird bei Bedarf wieder geöffnet.
/R

**Comment by mYnDstrEAm** [comment]
Feature request is here now, I'd reopen once Kodi has implemented this (which take quite a while if it's done): https://forum.kodi.tv/showthread.php?tid=369926

**Comment by mYnDstrEAm** [comment]
Vielleicht prgorammiert ja jemand anders als die Core-Entwickler einen Pullrequest.

Habe jetzt auch hier gefragt, wo es bis jetzt mehr Antworten gibt: https://www.reddit.com/r/kodi/comments/y207mh/can_it_be_possible_to_add_streams_documentaries/

**Comment by rols1** [comment]
ich versuche mal eine Behelfslösung: den Export von Videos aus der Merkliste zur Medienbibliothek. Die Ablage soll als strm-Datei (enthält nur die Video-Url, nicht das Video selbst) erfolgen. Mit dem  bereits erwähnten (strm-Modul)[https://github.com/rols1/Kodi-Addon-ARDundZDF/wiki/09.-strm-Modul] wäre eine Bereinigung denkbar (Löschen, falls nicht mehr in der Mediathek vorhanden).
/R

**Comment by rols1** [comment]
nach Auswertung des Merkliste-Moduls : **einen Export von Videos aus der Merkliste heraus kann ich leider nicht verwirlichen**. 
Grund: die Kontrolle wird nach Aktivierung eines Merklisten-Eintrags komplett an das aufgerufene Modul abgegeben. Theoretisch könnte ein entspr. Parameter mitgegeben werden. Dieser müsste aber über alle in Frage kommenden Funktionen weitergereicht werden. Da die mögliche Aufrufkette bis zu den einz. Videos sehr lang sein kann, würde dies einen immensen Aufwand bedeuten. Für ARD- oder ZDF-Videos wäre dies ev. noch leistbar, nicht aber für alle Module (arte, 3sat, phoenix, ..). 

Die umgekehrte Vorgehensweise habe ich ebenfalls geprüft (Abgleich einer beliebigenVideoliste mit Merkliste und Filter). Dafür wurde exemplarisch das arte-Modul erweitert: am Ende jeder Videoliste erfolgte ein Abgleich mit den Einträgen der Merkliste, einschl. gesetztem Filter. Das war soweit erfolgreich. Aber auch hier müsste noch die Url für jedes einzelne Video  ermittelt werden. Hier habe ich die Erweiterung abgebrochen,denn der Aufwand für das ganze Addon wäre vergleichbar mit der ersten Variante.

Ich hatte vor der Prüfung als Muster den Sammeldownload bei den Podcast-Favoriten (Audiothek) im Auge. Wie sich herausstellte, ist diese Lösung für die Merkliste nicht verwendbar. Dort ist der Aufwand für die Ermittlung der MP3-Quellen überschaubar.

**Alternativen im Addon**: 
1. Download (Setting "Sofortstart" AUS, auch via Kontextmenü möglich. Übrige Settings in Kategorie "Download Einstellungen"). Hier wäre für die Download-Tools neben dem Verschiebeverzeichnis eine zusätzliche Option machbar, die ein Verschieben der Downloads zu Verzeichnissen der Medienbibliothek ermöglicht. 
2. strm-Dateien (Settings in Kategorie "Favoriten / Merkliste / strm-Dateien"). Der strm-Export wurde in erster Linie für bstimmte Serien (nur ARD und ZDF) geschaffen, steht aber auch für einzelne Videos im Kontextmenü zur Verfügung (Sofortstart  EIN). Hier wäre ebenfalls eine zusätzliche Option zur Ablage in der Medienbibliothek möglich.

In beiden Fällen könnte man die Merkliste zum Filtern verwenden. **Beispiel**: 
Eintrag für "Astronomie - Alle Videos" anlegen und dem Ordner Doku/Wissen zuordnen. Dann den Eintrag anwählen und die einzelnen Videos entweder nach Alternative 1 oder 2 behandeln.   
/R
