### ISSUE TITLE
Videos/Serien mit Altersbeschränkung

### ISSUE THREAD

**Issue by nicro87** [rols1/Kodi-Addon-ARDundZDF#18]
Hallo,
ist es möglich Videos mit Altersbeschränkung anzusehen? In der Ard-Mediathek App funktioniert das glaub ich nur mit einem Account und einer hinterlegten Pin.

Vielen Dank,
Nico

**Comment by rols1** [comment]
Ja, über die MediathekViewWeb-Suche im Addon (Setting "MediathekViewWeb-Suche verwenden" in der Kategorie "Allgemein"). Dank eines stündlichen Scans durch MediathekView können Videoquellen auch außerhalb der Schutzzeiten zur Verfügung gestellt werden. Voraussetzung ist natürlich, dass ein Video in der Nacht vor der Suche bereits in der Mediathek existierte.
Login und Alterverfifikation konnten im Addon bisher nicht umgesetzt werden.
/R

**Comment by nicro87** [comment]
Vielen Dank! Werd ich mal probieren.
