### ISSUE TITLE
Das Erste live starts 2h back.

### ISSUE THREAD

**Issue by midnightflash** [rols1/Kodi-Addon-ARDundZDF#19]
Since some days just and only "Das Erste" starts live-tv 2h back in time from the Überregional menu. Same problem on two quite different systems: Linux desktop (Arch) with Kodi 19.4 and Android TV 9 with Kodi 19.3. Both using add-on-version 4.4.0.

Thanks in advance!

**Comment by rols1** [comment]
I've got the same issue via mail few days ago. Today I can reproduce this behavior. It seems to be a problem with inputstream.adaptive. In Addon-version 4.3.8 we had this problem with the subtitle livestreams of ARD.
OK - the workaround now is the same: the addon waits for Kodi-player and then set the seek-position 2 hours ahead.
Please, force a Einzelupdate as scribed [startpost on kodinerds](https://www.kodinerds.net/index.php/Thread/64244-RELEASE-Kodi-Addon-ARDundZDF/?postID=502022#post502022).
/R

**Comment by midnightflash** [comment]
That workaround did it on the desktop system, while the android TV still has the problem. Doesn't matter too much though. Will wait for the next .1 update.

**Comment by rols1** [comment]
i still have no explanation why the inputstream.adaptive addon has problems with the ARD stream.
For the workaround, the previous delay of 500 milliseconds between start of the Kodi player and manual Seek correction sometimes seems to be too short - especially on slower systems. I have now extended the delay up to 1 second. This has helped with my Raspi 3b+.
Of course, I would prefer a solution for the causal problem..
The current workaround is already available with the single update for util.py - or at weekend with update V4.4.1
/R

**Comment by midnightflash** [comment]
I forgot to tell you that I had to increase the delay in util.py manually in steps to 2500ms to make it work as desired most of the times on my Android TV. Those machines are very poor on the hardware side. So you should not care to much. Thank you to give me a way to deal with it myself.

**Comment by rols1** [comment]
thanks for the feedback. I note the solution for others concerned.
/R

**Comment by rols1** [comment]
bei Anpassungen an die geänderte [sportschau.de-Seite](https://www.sportschau.de/) festgestellt: **Livestreams des WDR** starten ebenfalls am Anfang des Puffers.
Für weitere Hinweise und Auffälligkeiten in Verbindung mit inputstream.adaptive bleibt dieser issue weiter geöffnet.
/R

**Comment by midnightflash** [comment]
The inputstream.adaptive add-on got updated right now. To me it looks like the error is gone with it.

**Comment by rols1** [comment]
that would be nice - unfortunately inputstream.adaptive is included as precompiled binary on my systems and an updates are not  possible yet
/R

**Comment by rols1** [comment]
today tested with Leia, Matrix and Nexus - works correct. Manuell seeking to bufferend is  no longer required. Now removed in PlayVideo() (modul util). 
issue closed.
