### ISSUE TITLE
Not compatible with Kodi 19 (Matrix)

### ISSUE THREAD

**Issue by BugDeliverer** [rols1/Kodi-Addon-ARDundZDF#2]
Kodi 19 (Matrix) has dropped Python v2.x (EOL) and uses Python 3.
The plugin requires Python 2 as a dependency.

**Comment by rols1** [comment]
an initial testversion for Kodi-Matrix (alpha) you can get there: [plugin.video.ardundzdf-x.x.x+matrix.zip](https://c.gmx.net/@327723216099344844/cASZJUNuQpqlEImIS62dmA).
The intern update-modul allows to get the following updates from the github-repo here.
Or you can use the kodinerds-repo to choose between leia-/krypton- or matrix-version.
