### ISSUE TITLE
ARD Livestream mit Dropouts und hoher CPU-Last

### ISSUE THREAD

**Issue by knutzone** [rols1/Kodi-Addon-ARDundZDF#20]
Hallo,
auf meinem Odroid N2+ gibt es beim Nutzen des Livestrams von Das Erste in kurzen Abständen immer wieder Dropouts (Bild- und Tonaussetzer), unabhängig von der gewählten Auflösung oder Framerate. Dazu konnte ich beobachten dass die CPU-Last kurz vorher immer ruckartig ansteigt und nach dem Dropout wieder zurückgeht. Dieses Verhalten tritt nur bei diesem Stream auf, alla anderen (ZDF, ARTE, usw.) laufen auch bei 1080p flüssig. Eine Vermutung wäre das Speichermanagement des Streams (vielleicht wg. Rückspulfunktion?), welches sich offenbar verändert hat. Im Beispiel läuft das Vidoe im Hintergrund und im Vordergrund erscheinen die Systeminformationen mit Monitoring von CPU und Speicher.

https://user-images.githubusercontent.com/79137857/174769310-06154239-3b0d-454b-a891-6e0e4d12953c.mp4

**Comment by rols1** [comment]
> auf meinem Odroid N2+ gibt es beim Nutzen des Livestrams von Das Erste in kurzen Abständen immer wieder Dropouts (Bild- und Tonaussetzer), unabhängig von der gewählten Auflösung oder Framerate.

vermutlich verwendest du das **inputstream.adaptive-Addon**, um den 2-Std-Puffer nutzen zu können. Tatsächlich scheinen bisher nur die ARD-Livestreams betroffen; allen voran **DasErste**. Aus dem Support entnehme ich 2 Phänomene: einmal der **Start am Anfang des Puffers** (im Verschiebebalken kann man die Kapitelmarken erkennen) und zum anderen die von dir erwähnten **Dropouts**. 
Das Addon ARDundZDF kann lediglich manuell die Position im Puffer korrigieren. Dazu existiert ein Workaround für den Untertitelstream DasErste, zuletzt erweitert für den normalen DasErste-Stream in Version 4.4.1.

Laut Hinweis auf der Entwicklerseite für das [**inputstream.adaptive-Addon**](https://github.com/xbmc/inputstream.adaptive/) wird **für jedes Segment des Streams ein eigener Prozessfaden** verwendet (This addon uses threads to download segments. The memory consumption is the sum of single segment from each stream currently playing. Refering to known streams it is < 10MB for 720p videos.) Bei einigen Megabits pro Stream Bitrate - je nach Auflösung - kann sich der Speicherbedarf schnell aufschaukeln.
Von daher kann es sich bei Dropouts tatsächlich um Speicherprobleme handeln. Um das zu prüfen, kann das Verhalten im Addon ARDundZDF **mit und ohne inputstream.adaptive-Addon verglichen** werden. Das Setting befindet sich in der Kategorie "Modul-Einstellungen".
Sollte ein Abschalten nicht helfen od. nicht gewünscht sein, lassen sich im inputstream.adaptive-Addon **Bandbreite und Auflösung herabsetzen**. Eine ähnlicher Hinweis findet sich hier: [Videos stuttering problem](https://github.com/xbmc/inputstream.adaptive/wiki/User-FAQ#videos-stuttering-problem).

Ob das Entwickler-Team von inputstream.adaptive hier Abhilfe schaffen kann, vermag ich nicht abzuschätzen. Den betroffenen Nutzern steht es frei, das Problem per issue zu melden.
/R

**Comment by knutzone** [comment]
Danke für die schnelle Reaktion! Ja, das mit dem Anfangsstand der Streams war mir auch schon aufgefallen, allerdings stört es mich nicht zu sehr da ich ja zur gewünschten Stelle vorspulen kann. Zu dem "Videos stuttering problem" kann ich nur sagen dass es beim Odroid N2+ eher weniger ein Problem mit einer zu schwachen CPU sein kann, da der eigentlich mit seinen sechs Kernen und 4Gb/16GB Speicher genug Powewr haben sollte. Immerhin reicht es für 4K 60p auf Netflix 
Und wie schon eigangs erwähnt sind die Aussetzer Auflösungsunabhängig (getestet mit 720x480 - gleiches Resultat). 
Ich wrde es mal mit dem Weglassen des Inputstream.addaptive versuchen, allerdings war eben genau diese Rückspulfunktion das besonders attraktive an der Sache...

**Comment by rols1** [comment]
> Zu dem "Videos stuttering problem" kann ich nur sagen dass es beim Odroid N2+ eher weniger ein Problem mit einer zu schwachen CPU sein kann

das meinte ich auch nicht. Ich hätte besser formulieren können "Speicherprobleme speziell beim Umgang mit ARD-Streams".
Vorrangig liegt das Problem augenscheinlich bei der Verarbeitung von ARD-Streams durch Inputstream.addaptive bzw. im weiteren Verlauf bei der ffmpeg-Bibliothek. Eine oder mehrere spezielle Eigenschaften der ARD-Streams scheinen ausschlaggebend zu sein. Tiefergehende Untersuchungen liegen aber jenseits meiner Fähigkeiten.
Leider kann mein Addon nach Übergabe von Livestreams an den Kodi-Player die Abspielqualität nicht beeinflussen, egal ob dabei  Inputstream.addaptive verwendet wird oder nicht. Immerhin verwenden die "Öffis" keine Verschlüsselung. so dass uns Probleme mit der widevine-Bibliothek i.V.m.  Inputstream.addaptive erspart bleiben.
/R

**Comment by knutzone** [comment]
Ok., nur zur Info: gestern Abend war wieder alles völlig normal, der Liverstream lief problemlos, ohne ruckeln und ließ sich auch ohne weiteres vor- und zurückspulen ohne dass ich irgendwas verändert habe! Das Problem scheint nun also aus der Welt. Wenn Du das warst dann vielen lieben Dank!

**Comment by rols1** [comment]
danke, aber  das kann ich leider nicht für mich verbuchen. Seit dem letzten Update am 16.6. gab es keinerlei Änderung im Addon zu den Streams.
Wenn das Phänomen Dropouts Dich wieder mal heimsucht, wäre ich für ein Debug-Log dankbar. Vielleicht ergibt sich dabei etwas Brauchbares für die weitere Suche. Bisher habe ich nur Debug-Logs vom Phänomen falscher Pufferstart.
Das Vorgehen wäre dann so:

- bei Auftreten von Dropouts Livestream abschalten (nicht nur pausieren)
- in den Settings "Allgemein" das Plugin-Logging einschalten
- Livestream wieder einschalten und Dropout abwarten (einer genügt)
- die Logdatei hochladen (z.B. auf https://paste.kodi.tv/) und den Link hier mitteilen

Den Ort für die Logdatei findest Du im Menü "Infos + Tools" / "Addon-Infos" / "Pfade"
/R
