### ISSUE TITLE
Problem mit 4.4.5 und LibreElec 9.2.8 

### ISSUE THREAD

**Issue by IgelCampus** [rols1/Kodi-Addon-ARDundZDF#22]
Mit dem Update auf 4.4.5 läuft das tolle Addon leider nicht mehr mit LibreElec 9.2.8. Der Fehler lautet:

```
Error Contents: No module named resources.lib.updater
```

Das manuelle Downgrade auf 4.4.4 lässt das Problem verschwinden.

**Comment by rols1** [comment]
Zur Ursache siehe [Forum kodinerds](https://www.kodinerds.net/index.php/Thread/64244-RELEASE-Kodi-Addon-ARDundZDF/?postID=689407#post689407) beschrieben. Dort findet sich auch ein Link zum Testaddon mit Fix.
Alternativ kann auch das aktuelle Release-Zip herunter geladen und installiert werden. 
**Vom Downgrade aus müsste auch ein Update mit dem addon-internen Updater klappen.**

Im nächsten offiziellen Update V4.4.6 ist der Fix enthalten, so dass die üblichen Updateverfahren wieder für Kodi Leia + Matrix funktionieren werden.
/R

**Comment by IgelCampus** [comment]
Danke!
