### ISSUE TITLE
Favorite list can't handle special characters

### ISSUE THREAD

**Issue by lepus2589** [rols1/Kodi-Addon-ARDundZDF#23]
The favorite list (Merkliste) is unable to handle special characters properly. An example for this is the ZDF show PUR+. If you add any part of the show to your favorites, the + character is missing. This prevents the entry from being removed from the list again. You have to navigate to where you added the entry from and remove it from there.

**Comment by rols1** [comment]
thanks - fixed in function ShowFavs, line 5242 (unquote_plus replaced from unquote). 
Fix is available via "Einzelupdate" in menu "Infos + Tools".
Please report if other characters are affected.
/R
