### ISSUE TITLE
No audio line selected when opening ARD/ZDF Live

### ISSUE THREAD

**Issue by Conlapped** [rols1/Kodi-Addon-ARDundZDF#24]
Whenever I open the ARD or ZDF Live-streams through this addon I have no audio, even though multiple audio streams are available. The Video OSD shows a questionmark where the audio line is supposed to be indicated. Only when I change the audio line manually then I'm hearing the audio.

I'm using Kodi 20 on AndroidTV (Nvidia Shield Pro 2019).

**Comment by rols1** [comment]
unfortunately I cannot reproduce the audio problem (Linux Ubuntu 22.04.1 LTS, Kodi Nexus 20.0, Nvidia Shield not available). Audio works here with DasErste and ZDF.
However, there is a subtitle problem since ARD and ZDF have changed their live stream formats - see https://github.com/xbmc/xbmc/issues/22582. There may be a relation.
/R
P.S. für dieses Addon supporte ich gerne auch in Deutsch..

**Comment by Conlapped** [comment]
Ich konnte das Problem ein bisschen spezifischer reproduzieren:
Wenn ich den ARD oder ZDF Livestream über das Addon öffne (Addon > Livestreams > Überregional > ARD/ZDF) dann funktioniert es wie erwartet inkl. Audio.
Ich habe diese beiden Streams jedoch meinen Favoriten hinzugefügt. Wenn ich sie dort starte, öffnet sich der Stream wie beschrieben ohne Audio bzw. ohne ausgewählte Audiospur.
Kannst du das bei dir ggf. reproduzieren?

**Comment by rols1** [comment]
keine Änderung bei mir. Zusätzlich habe ich die [Gigathek von 68000a](https://github.com/68000a/Gigathek) installiert und daraus ebenfalls DasErste-Live als Favorit getestet. Auch hier kein Problem mit dem Ton. 
Falls das Problem bei dir mit Kodi 19 nicht auftrat, lohnt sich vielleicht die Suche in einem spez. Forum für die Shield i.V.m. Kodi 20.
Alternativ könntest du es mit einer nightly-Version von Kodi20 probieren oder auch [Maven's Kodi-Builds für Android](https://www.kodinerds.net/index.php/Thread/69428-Maven-s-Kodi-Builds-f%C3%BCr-Android/).
/R

**Comment by Conlapped** [comment]
Danke für Maven's Kodi-Builds für Android, die kannte ich noch gar nicht. Leider tritt das Problem dort genauso auf. Die App behalte ich dennoch, da mich bei der App aus dem Playstore stört, dass die sich immer von selbst aktualisiert.

Die Gigathek ist auch ein toller Tipp und damit funktionieren die Streams auch aus den Favoriten. Dennoch ist dein ARDundZDF-Addon das beste und intuitivste Mediathek-Addon für Kodi, dass ich in den letzten Jahren hatte. Ich werds deshalb nicht aufgeben und ab und zu nochmal testen, vielleicht klappts ja mit dem nächsten Kodi Build. Für alle anderen Features kann ich es außerdem nutzen, nur das mit den Streams aus den Favoriten heraus ist halt schade.

**Comment by rols1** [comment]
> Die Gigathek ist auch ein toller Tipp und damit funktionieren die Streams auch aus den Favoriten.
Interessant. Dann lohnt es sich, es nochmal mit geänderter Einstellung "Sofortstart .." (Setting od. Kontextmenü) zu versuchen:
- Sofortstart EIN -> DasErste -> Favoriten
- Sofortstart AUS -> DaErste anklicken und "autom. | HLS-Stream" -> Favoriten
Der Aufrufmechanismus des Players unterscheidet sich je nach Setting Soforstart. Hier könnte ein Zusammenhang mit dem Tonproblem bestehen - wenn auch indirekt, denn programmtechnisch könnte ich keine kausale Verbindung benennen.
Andererseits: wenn es mit den beiden Livestreams aus der Gigathek klappt, ist das Problem aus Nutzersicht ja auch gelöst.
/R

**Comment by Conlapped** [comment]
Danke für die Anleitung. Konnte ich gut umsetzen, aber leider ohne Erfolg. Manchmal wird Audio direkt abgespielt, aber so gefühlt nur bei jedem 10. mal. Das war vorher auch schon der Fall, unabhängig vom Sofortstart.

Mir fällt außerdem auf, dass der Stream aus der Gigathek deutlich schneller startet, sowohl Video als auch Audio. Woran kann das liegen? Die Quelle ist ja vermutlich die selbe, oder?

**Comment by rols1** [comment]
die Quellen habe ich noch nicht verglichen - das hole ich nach und teile das Ergebnis mit. In ARDundZDF stammen sie direkt von der Webseite, es gibt aber noch Quellen via API-Calls oder Direktlinks aus iptv-Listen.
/R

**Comment by rols1** [comment]
deine Vermutung stimmt: die Streamlinks sind identisch (DasErste: https://mcdn.daserste.de/daserste/de/master.m3u8). Die Verzögerung sehe ich im vorgeschalteten Server-Ping (Test auf Verfügbarkeit). Im Code werden zusätzlich noch Subtitel, inputstreamaddon , interne Playlist und ev. Rekursionsprobleme berücksichtigt. 
/R

**Comment by Conlapped** [comment]
Die "Verzögerung" ist ja auch nicht erheblich und hat dann ja anscheinend seine Daseinsberechtigung.
Ich werd den Live-Stream von den Favoriten aus immer mal wieder testen, vor allem mit weiteren Kodi Builds. Bis dahin nutze ich den Live-Stream der Gigathek und die Mediatheken von ARDundZDF =)
