### ISSUE TITLE
Gesehene Videos markieren / Thumbnails ausblenden

### ISSUE THREAD

**Issue by SalieriC** [rols1/Kodi-Addon-ARDundZDF#25]
Möglicherweise habe ich die Einstellung dafür übersehen, aber ist es möglich die Kodi Standardansicht zu verwenden bei der in der Liste keine Thumbnails angezeigt werden, sondern ein Kreis/Häckchen? Oder ist es überhaupt möglich zu markieren was man bereits gesehen hat? Das wäre für mich ein sehr wichtiges Feature und wenn das derzeit nicht möglich ist betrachtet dies bitte als Feature Request.

Insgesamt aber ein wirklich gut gemachtes Add-On, vielen Dank dafür.

**Comment by rols1** [comment]
Das Setting "Setze Inhaltstyp TV-Shows (zeigt Abspielstatus für Videos)" in Kategorie "Modul-Einstellungen" müsste passen. Siehe auch [Wicki 08. Settings Module, Zif. 19](https://github.com/rols1/Kodi-Addon-ARDundZDF/wiki/08.-Settings-Module).
/R

**Comment by SalieriC** [comment]
Genau das habe ich gesucht, vielen Dank.
