### ISSUE TITLE
Empty popups on every menu change with 4.6.1

### ISSUE THREAD

**Issue by mhoyer** [rols1/Kodi-Addon-ARDundZDF#26]
I just updated today from 4.6.0 to 4.6.1 on my LibreElec 9.2.8 (on a Pi4) and now this great addon shows me an empty window when opening the addon and for every further deeper navigation step. I can close the window with the ok button on my virtual remote, still it's a bit annoying. Any clue what's causing it?

I already uninstalled and reinstalled the addon. No success.

![screenshot000](https://user-images.githubusercontent.com/76611/219173176-5a6e7739-29ae-4f0d-ab58-682181c11b36.png)

**Comment by rols1** [comment]
It's new for me. Please activate Plugin-Logging in Addon, restart Kodi and Addon and send me the Debug-Log (on Pi in /storage/.kodi/temp/kodi.log).
While I'm debugging you can install V4.6.0 from  [kodinerds-Repo](https://repo.kodinerds.net/index.php?action=list&scope=all&version=krypton/). I think Kodi 17 is correct for LibreElec 9.2.8.
We can talk in german here if you want.
/R

**Comment by rols1** [comment]
I don't need a debug-log - can reproduce the empty window..
/R

**Comment by mhoyer** [comment]
Na klar geht auch Deutsch. ;-)

Jetzt hatte ich den Logauszug schon fast abgeschickt. Ok. Ich bin gespannt.

**Comment by rols1** [comment]
in der Tat: die leere Dialog-Box  setzt sich in den Vordergrund. Ein Fehler im Addon ist nicht erkennbar. Ich vermute einen Zusammenhang mit der Task-Verwaltung i.V.m. der neuen Kontext-Option "EPG" in V4.6.1. Allerdings dauert das Problem nach Abschalten der Option an. 
Es braucht also leider mehr Versuche, um das Problem zu sondieren. Das könnte ein paar Tage dauern. Ein Downgrade wie bereits erwähnt hilft - gerade ausprobiert. Die kodinerds-Seite bietet unter dem jeweiligen Addon-Log einen Archiv-Button mit einigen älteren Versionen.
Es gibt wohl kaum noch RPi-Nutzer mit Kodi Leia, das wäre eine Erklärung für ausbleibende Meldungen dazu. Solange wie geht, werden aber weiterhin alle Versionen von Krypton bis Nexus mit einer Codebasis unterstützt.

**Comment by rols1** [comment]
gefixt oder besser: gepflastert. Hier der Beitrag im Forum:

> leeres Textfenster bei jedem Menüwechsel (nur Python-Version 2.*)

> das Phänomen wurde bisher nur beobachtet auf Linux Mint 19.3 und LibreElec 9.2.8 (beim Laden des EPG-Moduls). Siehe Bild.
> Nur wer davon betroffen ist, installiere bitte das Einzelupdate EPG.py. Dies ist trotz der Textfenster möglich.
> Dadurch entfällt leider auf diesen Systemen die mit dem letzten Update (V4.6.1) eingeführte Kontext-Option "EPG" im > > Menü TV-Livestreams.
/R

**Comment by rols1** [comment]
Lösung verbessert (**Einzelupdate EPG.py, util.py**):
im EPG-Modul sind für das Laden des Moduls util 2 Varianten erforderlich (1 x Aufruf aus Haupt-PRG, 1 x aus Kontextmenü). Bisher geschah dies via try/except, was bei Python 2.* zum leeren Textviewer-Fenster führte. 
Jetzt ist das Laden (des EPG-Moduls ist abhängig vom Inhalt sys.argv. Damit ist der Aufrufer unter allen Python-Versionen eindeutig identifizierbar.
Mit OK getestet auf Linux Mint mit Kodi Leia. Ich bitte um Rückmeldung zum Ergebnis auf LibreElec 9.2.8.
/R

**Comment by mhoyer** [comment]
Habe eben beide `.py` Files ausgetauscht und kann damit das Problem nicht mehr reproduzieren - das leere Fenster zeigt sich nicht mehr. :+1:

**Comment by rols1** [comment]
prima, danke. Dann kann ich mit done schließen.
Ich vergaß: mit der ergänzten Lösung steht das Kontext-EPG im Menü TV-livestreams auch für  die älteren Python-Versionen zur Verfügung.
/R

**Comment by mhoyer** [comment]
Top job. Vielen Dank für's scynelle Kümmern!

**Comment by rols1** [comment]
war mir ein Vergnügen, Helau/Alaaf  und bis zum Nächstenmal..
/R
