### ISSUE TITLE
Merkliste: fett-Formatierung bei Übernahme von gesuchten Sendungen

### ISSUE THREAD

**Issue by cpy82** [rols1/Kodi-Addon-ARDundZDF#29]
Hallo,

zunächst vielen Dank für dieses Tolle Addon und die damit verbundene Arbeit!

Ich habe wirklich nur eine rein kosmetische Anfrage: Wenn man in den Mediatheken nach einer Sendung sucht und das Suchwort komplett mit den Funden übereinstimmt, wird es ja im Sendungstitel fett hervorgehoben. Bei der Übernahme in die Merkliste bleibt die fett-Formatierung erhalten und taucht dann so wieder in der Merkliste auf. Steht es z.B. am Anfang, sind die Einträge eingerückt und insgesamt bei einigen Einträgen wirkt es merkwürdig.

Könnte man das vielleicht bei Übernahme in die Merkliste normalisieren?

Vielen Dank!

**Comment by rols1** [comment]
würde es reichen, die fett-Formatierung zu entfernen? Das wäre mit einer bereits vorhandenen Funktion einfacher zu verwirklichen als die Ursache für die Einrückung zu finden und zu beseitigen.

**Comment by rols1** [comment]
OK - Fix liegt vor. Er eliminiert Fett- und Farbmarkierungen im Titel von Einträgen der Merkliste und ist ab sofort via Einzelupdate von ardundzdf.py [siehe Wicki Einzelupdate (Dateien und Module](https://github.com/rols1/Kodi-Addon-ARDundZDF/wiki/01.-Settings---Allgemein#22-einzelupdate-dateien-und-module) verfügbar. Das für morgen geplante Update auf V4.7.6 wird voraussichtlich um eine Woche verschoben (keine gravierenden Änderungen vorhanden).
Hinweis: auf meinem PC (Linux, Kodi  Matrix) konnte ich vor dem Fix keine Beeinträchtigung mit fett-markierten Titeln feststellen.

**Comment by rols1** [comment]
pardon - ich musste nochmal nachbessern (neues Einzelupdate von ardundzdf.py). Die verwendete Funktion cleanmark() lässt ein Leerzeichen am Anfang + Ende des Titels zurück (fiel mir erst mit der Bildschirmlupe auf).
Mit "Beeinträchtigung" meinte ich, dass ich keine deutlichen Einrückungen sehen konnte. Das kann aber auch mit der variablen Schriftbreite je nach Buchstaben im markierten Teil zusammenhängen, falls nicht Arial verwendet wird - oder auch mit meiner Dioptrienzahl.

**Comment by rols1** [comment]
ich habe es jetzt das Einzelupdate erneut eingespielt, ebenfalls mit LibreElec 11.0.1 auf RP  3+ - hier problemlos. 
Neustart von Kodi  / Gerät sollte bei dir helfen. Bei Bedarf schaue ich mir gerne das Debug-Log an (mit aktiviertem Plugin-Logging in den Addon-Settings).

**Comment by rols1** [comment]
ich denke, die Ursache liegt im fehlenden Einzelupdate von tools.py. Das war im Startpost des Forums kodinerds das letzte Einzelupdate, das zusätzlich zum Datum auch die letzte Update-Info für das menü "Infos & Tools" liefert. 
Das lässt sich bei dir jetzt nicht mehr mit Einzelupdates heilen. Ich stelle morgen ein Testaddon zur Verfügung, das alle aktuellen Änderungen enthält. Debug-Log ist vorerst nicht erforderlich.

**Comment by rols1** [comment]
> ja, ich hatte ich auch schon Abhängigkeiten zu etwas anderem vermutet. Ich hab das Addon dann einmal neu installiert und dann das neue Einzelupdate ardundzdf.py eingespielt.

prima - gut gelöst. Damit erübrigt sich das Testaddon.
> Sorry, für diese generell eher "pingelige" Anfrage mit der Merkliste.

kein Ding, gerne wieder.  Viel Spaß noch mit dem Addon..

**Comment by rols1** [comment]
Merkliste: Ergänzung zum vorigen Einzelupdate (Löschen von fett-markierten Einträgen war nicht mehr möglich) - Einzelupdate merkliste.py.
Hinzufügen von Einträgen ist nicht betroffen - dort erfolgt der Abgleich direkt mit der Datei merkliste.xml.
