### ISSUE TITLE
Installing 3.7.5 on matrix

### ISSUE THREAD

**Issue by monochromec** [rols1/Kodi-Addon-ARDundZDF#3]
Gives the following error message: 

 CAddonInstallJob[plugin.video.ardundzdf]: The dependency on xbmc.python version 2.25.0 could not be satisfied.

Installed from the downloaded zip file.

**Comment by monochromec** [comment]
More than happy to provide more information - just let me know. Happy to help!

**Comment by monochromec** [comment]
Installing this plugin from the repo works OK.

**Comment by rols1** [comment]
yes, the download version on Github is not accepted by Matrix during the initial installation - I will add this in the readme.
On following updates with the addon-internal updater, the Github version adjusts to the local Kodi version.
/R
