### ISSUE TITLE
 inputstream.adaptive: Einblendung der Stream-Uhrzeit für die Position im Zeitpuffer 

### ISSUE THREAD

**Issue by fenjen** [rols1/Kodi-Addon-ARDundZDF#30]
Halle

Wenn ich den Livestream von ZDF einschalte und zurückspule, bekomme ich eine etwas ungewöhnliche Zeitanzeige dargestellt: Es sieht so aus, als wenn der Ankerpunkt "03:00:00" ist, wenn ich 10 Minuten zurückspule, steht dort "02:50:00 / 03:00:00". Vermutlich liegt es daran, dass der Live-Stream immer 3h zurückreicht, aber das macht das Spulen an eine bestimmte Stelle sehr schwierig. Ein normaler Anwendungsfall ist wohl, dass man auf exakt 19:00 Uhr oder 20:15 Uhr spulen möchte - mit der Darstellung muss man dann rechnen. Ein zweiter Anwendungsfall ist, dass man zu einer bestimmten Stelle zurückgehen möchte. Das ist ohne Ausprobieren gar nicht möglich.

Vielen Dank für das Add-On!

**Comment by rols1** [comment]
ja, das missfällt mir auch und richtig: das ZDF hat einen 3-Stunden-Zeitpuffer beim Livestream - den größten der Sender von ARD und ZDF.
Leider ist es addonseitig nur eingeschränkt möglich, den Scrollmechanismus der Pufferanzeige zu beeinflussen. Das Addon übergibt in  der Funktion PlayVideo() im Modul util die Kontrolle an das inputstream.adaptive-Modul. Die xbmc-Schnittstelle erlaubt lediglich eine beschränkte Anzahl von [zeitbezogenen Funktionen](https://codedocs.xyz/xbmc/xbmc/group__python__Player.html) wie z.B. Player.getTime()  und Player.seekTime(). Das Koppeln des Zeitpuffers an die lokale Zeit, einschließlich der korrekten Korrektur der Zeitanzeige beim Spulen ist für Addon-Entwickler (Kodi-Stand z.Z.) nicht möglich.
Tut mir leid, aber hier kann ich nicht helfen.

**Comment by fenjen** [comment]
Das heißt, man hat keinen Einfluss auf das Seeking-Verhalten, weil das alles die XBMC-Funktionen selbst machen? (Sonst könnte man ja hin und her übersetzen.) Hm, Ist es vielleicht möglich, eine Art Toast-Notification einzublenden?

**Comment by rols1** [comment]
Doch, ich kann den Puffer sekundenweise vor - und zurücksetzen. Das mache ich auch in der addoninternen Playlist, um an einer abgebrochenen Stelle fortzusetzen. Damit erschöpft sich aber auch schon das seeking. Ich kann dagegen nicht einen Layer über die Pufferanzeige legen und zwischen dem Layer und  inputstream.adaptive übersetzen. Zwar wäre theoretisch die Anzeige mit einem zusätzlichen Skin-Element machbar. Eine Hintergrundroutine müsste dann ständig die Seek-Position auslesen und in eine Zeitanzeige im Layer übersetzen. Vielleicht ist es machbar, aber das würde ich gerne jemandem überlassen, der hierzu besonders motiviert ist (und mehr Zeit hat als ich).

**Comment by fenjen** [comment]
Ja, an eine weitere Anzeige _über_ der Standardanzeige hab ich auch schon gedacht, aber ich ging auch davon aus, dass das etwas komplizierter ist. Das Übersetzen meinte ich in etwa so:
```
player.setStartTime(now - 3h)
player.setEndTime(now)
player.onSeek(value -> stream.seek(current + value))
```
Aber ich kenne weder den XBMC-Code noch den Addon-Code :) Und darüber hast Du sicher auch schon nachgedacht.

Eine Toast-Notification ist eine Art Popup-Element, das nach kurzer Zeit wieder verschwindet. In so einem Popup könnte man beim Seeken die aktuelle Stream-Realzeit (zusätzlich) darstellen.

**Comment by rols1** [comment]
Ah ja, dann meint Toast-Notification die bekannte Funktion  xbmcgui.Dialog().notification() - danke.
Im Prinzip würde das Übersetzen so klappen. Das Problem ist der Aufwand für den Skin - selbst allein für den Default-Skin Estuary.  Im Addon habe ich in wochenlanger Arbeit eine Slideshow mit skin-Elementen realisiert - was für ein Aufwand. Zusätzliche skin-Elemente gehen m.E. weit über ein normales Mediathek-Addon hinaus. 
Wie gesagt, ev. findet sich im Kodi- oder Kodiners-Forum ein motivierter Nutzer, der das Addon forkt und sein Glück versucht..

**Comment by fenjen** [comment]
Das heißt, man könnte theoretisch `xbmcgui.Dialog().notification()` nutzen, um bei einem Aufruf von den [Callback functions from Kodi to Add-On](https://codedocs.xyz/xbmc/xbmc/group__python__PlayerCB.html), also beim Seeken `XBMCAddon::xbmc::Player::onPlayBackSeek (int time, int seekOffset)` die korrekte Zeit einblenden. Schön wäre es vermutlich nicht. Aber bräuchte man denn die Hintergrund-Routine, wenn man das Callback hat? Müsste ja nur bei Bedarf angezeigt werden.

OK, aber mehr Ideen hab ich auch nicht :) Danke jedenfalls!

**Comment by rols1** [comment]
[xbmcgui.Dialog().notification()](https://alwinesch.github.io/group__python___dialog.html) ist auf den verschiedenen Systemen zu unsicher. Eine durchgehende Anzeige ist nicht garantiert. 
Tatsächlich braucht es den Background-Task grundsätzlich nicht , stimmt. Andere benötige Tasks, wie z.B. Downloads oder Serienüberwachung können weiterlaufen, wenn die Übersetzungsschleife regelmäßig xbmc.sleep() verwendet und damit ein Blockieren verhindert.

**Comment by fenjen** [comment]
Ich dachte, einfach bei Seek ausgeben:
```python
import time, datetime as dt
HOURS = 60 * 60

def XBMCAddon_xbmc_Player_onPlayBackSeekonPlayBackSeek(position, seekOffset):
    now = dt.datetime.now()
    position = now - dt.timedelta(0, 3 * HOURS) + dt.timedelta(0, position)
    position = position.strftime("%H:%M:%S")
    endTime = now.strftime("%H:%M:%S") 
    # player.setStartTime(position)
    # player.setEndTime(endTime)
    print(position + " / " + endTime)

XBMCAddon_xbmc_Player_onPlayBackSeekonPlayBackSeek(2 * HOURS, 0) # position=2 hours (of 3)

**Comment by rols1** [comment]
ich habe auf die Schnelle eine kurze Testroutine erstellt, welche die seek-Position anzeigt. 
Damit kannst du erstmal das Antwortverhalten beim Verschieben testen. 
Für die spätere Übersetzung in eine Zeitangabe bitte die unterschiedlichen Zeitpuffer der Sender beachten - 3 Std. ist die Ausnahme.

Funktion ShowSeekPos() im Modul util:
`
def ShowSeekPos(player, url):
	PLog('ShowSeekPos:')

	icon=""
	if url.endswith('.m3u8') and SETTINGS.getSetting('pref_inputstream') == 'true':
		while player.isPlaying():
			xbmc.sleep(500)	
			play_time = player.getTime()
			p = str(int(play_time))
			xbmcgui.Dialog().notification("PlayTime: ",p,icon,500, sound=False)
	
	return
`

Aufruf in Funktion PlayVideo  im Modul util, hinter dem Aufruf für Untertitel:
`
			PLog('PlayVideo_Start: listitem')
			xbmcplugin.setResolvedUrl(HANDLE, True, li)			# indirekt						
			while 1:											# showSubtitles nur bei akt. Player wirksam
				if player.isPlaying():
					xbmc.sleep(1000)							# für Raspi erforderl. (500 können fehlschlagen)
					if SETTINGS.getSetting('pref_UT_ON') == 'true':
						PLog("Player_Subtitles_on")
						xbmc.Player().showSubtitles(True)
					else:		
						PLog("Player_Subtitles_off")
						xbmc.Player().showSubtitles(False)									
					break
				xbmc.sleep(200)
			ShowSeekPos(player, url)
			return
`

**Comment by rols1** [comment]
Leider habe ich z.Z. Probleme mit den Code-Tags in meinem Browser..

**Comment by rols1** [comment]
ich habe auf die Schnelle eine kurze Testroutine erstellt, welche die seek-Position anzeigt. 
Damit kannst du erstmal das Antwortverhalten beim Verschieben testen. 
Für die spätere Übersetzung in eine Zeitangabe bitte die unterschiedlichen Zeitpuffer der Sender beachten - 3 Std. ist die Ausnahme.
Funktion ShowSeekPos() im Modul util:
[code1.txt](https://github.com/rols1/Kodi-Addon-ARDundZDF/files/11780982/code1.txt)

Aufruf in Funktion PlayVideo  im Modul util, hinter dem Aufruf für Untertitel:
[code2.txt](https://github.com/rols1/Kodi-Addon-ARDundZDF/files/11780983/code2.txt)

**Comment by fenjen** [comment]
Hi! Oh, spannend! Ich weiß ehrlich gesagt gar nicht, wie man Kodi-Plugins schreibt oder einspielt (und Python ist gar nicht so meine Programmiersprache). Ich hatte Dein Addon damals über die integrierte Addon-Suche installiert.

Ich hab mal ein Diff gemacht zwischen der util.py und der aktuellen Version von Github. Wenn ich die `5000` in dem `xbmc.Dialog().notification()`-Aufruf richtig deute, vermute ich mal, dass die Notification für 5s angezeigt wird. Spontan würde ich annehmen, dass 2s ausreichen würden. Und ich würd wahrscheinlich nur "Uhrzeit" schreiben, weil "Puffer" für normale Menschen zu technisch ist :)

Ich hab mal ganz naiv die util.py auf meinem Raspberry Pi durch die von Dir angehängte ersetzt, aber da sehe ich auch nahc Reboot keine Notification.

**Comment by rols1** [comment]
auf dem PC (Linux mit Kodi 19) funktioniert es mit fast allen getesteten Livestreams mit unterschiedlichen Pufferlängen prima. Leider bleibt ein bei Events stark nachgefragter [aktueller ARD-Sportschau-Stream](https://ardevent2.akamaized.net/hls/live/681512/ardevent2_geo/index.m3u8) bei der player.isPlaying()-Schleife hängen. Ev. ist für wenige Ausnahmen doch ein Background-Task erforderlich.
Ich mache morgen einen Test mit meinem Raspi 3b+ (LibreElec 11.0.1, Kodi Nexus 20.1). Wenn das Ergebnis dem PC-Ergebnis entspricht, stelle ich das Modul util.py als Einzelupdate im kodinerds-Forum zur Verfügung - [siehe Wicki Einzelupdate (Dateien und Module](https://github.com/rols1/Kodi-Addon-ARDundZDF/wiki/01.-Settings---Allgemein#22-einzelupdate-dateien-und-module). Das lässt sich im Addon einfach einspielen.

Stimmt: 5000 entspricht 5 sec. Anzeigedauer - könnte man auch durch ein Setting variabel machen.
Zur Meldung "Puffer-Uhrzeit": ich tendiere eher zu "Stream-Uhrzeit". "Uhrzeit" allein kann irritieren. Ein Bezug ist m.E. erforderlich, um sich von der durch Kodi angezeigten Zeit (einschl. "endet um..") abzugrenzen.

Screenshot (Pfeile nachträgl. eingefügt):
![Pufferzeit](https://github.com/rols1/Kodi-Addon-ARDundZDF/assets/12525055/9f2c29b4-3ecc-4731-ab58-81355ec34d6f)

**Comment by fenjen** [comment]
Das sieht doch super aus! "Stream-Uhrzeit" find ich auch gut!

Hab auf meinem Raspberry Pi die aktuelle OSMC-Version installiert. Reicht es nicht, die util.py auf dem System direkt zu ersetzen (hab eh eine Samba-Freigabe, daher ist das sehr komfortabel)? Wenn es theoretisch ausreichen sollte, würd ich mal das Logging einschalten und prüfen, wo es hakt.

**Comment by rols1** [comment]
Ersatz von util.py reicht hier. Ich würde aber mit Logging noch warten, bis ich eigene Erkenntnisse aus den Tests auf meinem Raspi habe. Ev. muss noch nachgebessert werden.

**Comment by rols1** [comment]
Mit Setting "Untertitel: falls vorhanden, im Player einschalten" funktioniert die Anzeige auch beim Raspi. Es ist wohl so - wie auch in anderen Fällen - dass bei schwächerer Hardware zusätzl. Zeit benötigt wird. Fortsetzung heute Nachmittag/Abend.

**Comment by rols1** [comment]
die aktuelle Funktion kann mit Einzelupdate util.py und  settings.xml installiert werden. Im Setting (Kategorie "Modul-Einstellungen") ist die  "Stream-Uhrzeit" freizuschalten.
Mit schwächeren Systemen funktioniert es nur mit einzelnen Streams. Dto bei Sync-Problemen, die inputstream beim Starten oder Verschieben haben kann. Daher die Voreinstellung AUS beim Setting.
Mal schauen, ob sich mit der Funktion als Task eine Verbesserung ergibt.

**Comment by rols1** [comment]
issue-Titel geändert - im Addon ist eine Unterscheidung Live-/Videostream z.Z. nicht möglich.
