### ISSUE TITLE
PlayTime: xxxx shown in Livestream

### ISSUE THREAD

**Issue by matz585** [rols1/Kodi-Addon-ARDundZDF#32]
Hi there,

since automated update yesterday, there is an info box shown while playing any livestream.
This box only vanishes after restart.

Thank you for any help or guidance.

Thanks and Regards
Matthias

![20230619_205732](https://github.com/rols1/Kodi-Addon-ARDundZDF/assets/78071782/3191936c-bd48-46f5-9a68-902d00f9e570)

**Comment by rols1** [comment]
ja, leider hatte ich beim Update versäumt, eine kleine Testroutine auszukommentieren. Hier die Lösung (kodinerds-Support-Thread) von gestern:
![util](https://github.com/rols1/Kodi-Addon-ARDundZDF/assets/12525055/5c178590-bd40-4790-8c59-fd3f1b729c87)

**Comment by rols1** [comment]
Btw: ich empfehle bei ähnlichen Problemen, den [Support-Thread](https://www.kodinerds.net/thread/64244-release-kodi-addon-ardundzdf/) zu nutzen. Auftretene Störungen versuche ich tagesaktuell über Einzelupdates zu beseitigen und die Reichweite ist dort wesentlich größer als hier.
