### ISSUE TITLE
"Quelle nicht erreichbar oder nicht mehr vorhanden." Fehlermeldung

### ISSUE THREAD

**Issue by SalieriC** [rols1/Kodi-Addon-ARDundZDF#33]
Hallo.

Vor einigen Tagen ist meiner Freundin eine Fehlermeldung beim Versuch die aktuellen Folgen einer Rubrik zu sehen aufgefallen. In diesem Fall bei der Kategorie ARD -> Rote Rosen. Beim Versuch die aktuellen Folgen der Kategorie zu sehen erscheint die folgene 
Fehlermeldung:
```
Fehler in ARD StartRubrik: Rote Rosen - Aktuelle Folgen
Quelle nicht erreichbar oder nicht mehr vorhanden.
get_page1 - get_page3 fehlgeschlagen. | unknown url type: "
```

**Comment by rols1** [comment]
Hallo,
bitte das Einzelupdate ARDnew.py installieren (Menü Infos+Tools, Einzelupdate, wie hier beschrieben: https://www.kodinerds.net/thread/64244-release-kodi-addon-ardundzdf/?postID=502022#post502022 ).
Es gab in den letzten Tagen eine Reihe von Änderungen bei der ARD.
Damit klappte soeben der Zugriff auf alle Folgen via A-Z/R.

**Comment by SalieriC** [comment]
Das hat geholfen, danke.
