### ISSUE TITLE
ARD Mediathek wird nicht geöffnet

### ISSUE THREAD

**Issue by Githopperle** [rols1/Kodi-Addon-ARDundZDF#39]
Version 5.07 macht Probleme bezüglich der ARD-Mediathek. Diese lässt sich unter LibreELEC 12.0 (Kodi 21.0) nicht öffnen. Nach dem Anwählen erscheint für ein paar Sekunden der "Warte-Kreis". Danach verschwindet dieser, die Inhalte der Mediathek werden jedoch nicht angezeigt sondern weiterhin die Startseite des Plugins.

Eine Neuinstallation des Plugins brachte keine Verbesserung, aber ein Downgrade auf Version 5.06 beseitigte das Problem. Es müsste also irgendwas mit dem letzten Update zu tun haben...

**Comment by Githopperle** [comment]
Problem per Mail gemeldet.

**Comment by rols1** [comment]
Probleme bestehen z.Z. mit der ZDF-Mediathek (api-Problem, siehe [Forum Kodinerds)](https://www.kodinerds.net/thread/64244-release-kodi-addon-ardundzdf/?postID=759671#post759671).
Für die ARD-Mediathek kann ich das Problem mit meinem Raspi, LibreElec 11.95.1., Kodi 21.0-RC1, nicht nachvollziehen. Denkbar wäre aber, dass der Hintergrund-Task des EPG klemmt. Dazu bitte (falls aktiviert) im Setting  "Recording TV-Live" das "EPG im Hintergrund laden.." abschalten.
Ein weiterer "Störenfried" könnte der Hintergrund-Task für die Livestreamquellen sein. Hier kann ein Refresh der Quellen über das Menü Infos+Tools -> Refresh: Addon-Cache.. helfen.
Allerdings wurden beide Funktionen beim letzten Update nicht verändert. Ev. benötige ich für die Analyse ein Debug-Log (bitte an die Aktivierung im Setting Allgemein denken).

**Comment by rols1** [comment]
Das Update V5.0.8 mit den Änderungen zum ZDF-Bereich ist gerade raus. Ich konnte jedoch auf meinem Raspi (ebenfalls mit Kodi Omega) keine Probleme feststellen (weder vor noch nach diesem Update). Falls der Fehler noch exisitiert, bitte ich um ein oder zwei konkrete Fehlerbeschreibungen zum Nachstellen des Problems - zunächst mal ohne Debug-Log

**Comment by rols1** [comment]
Fehler gefunden: eine Variable beim Untermenü ist nicht vorbelegt. Bitte die "MediathekViewWeb-Suche" in Kategorie "Allgemein"  freischalten - dann funktioniert es. Da die meisten Nutzer diese Option eingeschaltet haben, trat der Fehler nur selten auf.
Einzelupdate für ARDnew.py folgt morgen..

**Comment by Githopperle** [comment]
Vielen Dank für die schnelle Lösung!
Super Plugin! 👍
