### ISSUE TITLE
Feature request: Links teilen ählich wie youtube addon

### ISSUE THREAD

**Issue by carlos22** [rols1/Kodi-Addon-ARDundZDF#40]
Ich weiß leider nicht wie schwer so etwas wäre, aber ab und zu habe ich mediathek links wie das hier z. B. https://www.ardmediathek.de/video/Y3JpZDovL3dkci5kZS9CZWl0cmFnLXNvcGhvcmEtMDY5Y2M5N2MtZmViZC00YjFjLTk2NzItYTc0Yzk3ODM0N2E3 und da wäre es toll wenn man das via kore direkt teilen könnte an kodi und der das abspielt. Ich weiß das die APIs teilweise sehr verworren sind und die IDs unterschiedlich usw. Aber ggf. wäre es ja auch möglich nur eine Suche zu starten mit einem gescrapten titel von der Seite (ebenso bei ZDF) das würde schon viel helfen. Aktuell kopiere ich quasi titlel in die Suche und das klappt auch nicht immer gut.

Ansonsten ist das ein genails Plugin und auch die konstante Anpassung ist beeindruckend!

**Comment by rols1** [comment]
1. **zum Teilen**: für das Teilen von Inhalten auf mobilen Geräten zu Kodi gibt es meines Wissens keine geeignete Schnittstelle. Es existieren zwar die Remote-Procedure-Calls (RPC-Calls) bei Kodi und auch ein API dazu. Der entsprechende Aufruf müsste aber von der aufrufenden App (kore, yatse, ..) erfolgen.  Zusätzlich müsste im Addon erst ein Mechanismus geschaffen werden, der die Werte aus dem RPC-Call übernimmt und verarbeitet. Für beides sehe ich leider keine Chance zur Verwirklichung. 
2. **zur Suche:** wenn ich es richtig verstehe, geht es um die Suchfunktion im Addon, wo ein Text in das das Suchformular manuell eingetragen wird? Mich irritiert der Begriff "**kopiere**". Sollte es möglich sein, jetzt schon in einer neueren Kodi-Version das Suchformular mittels copy & paste zu füllen. dann würde sich eine Möglichkeit für eine Erweiterung der Suchfunktion anbieten, z.B. eben für den Link zu einer Sendung. Das klingt interessant und würde ich auch versuchen umzusetzen. Bei den Kodi-Versionen, die ich momentan für den Support nutze (keine nightly-Builds), muss allerdings das Suchformular noch Buchstabe für Buchstabe gefüllt werden.

**Comment by carlos22** [comment]
1. Ah ok das wusste ich nicht, bei youtube funktioniert es mit kore (dem offiziellen) und es gibt halt noch das hier, das kann noch mehr platformen und man kann auch einstellen auf welches plugin das gehen soll. Sieht für mich schon so aus als ob man das da recht gut übergeben könnte: https://apt.izzysoft.de/fdroid/index/apk/com.isayso.fire2kodi

 
4. Ja ich kopiere das via Kore, und der "tippt" es dann soweit ich weiß eben ein in Kodi. Da gibts direkt im Kore so eine funktion um die eingaben über das handy zu machen und das funktioniert dann auch mit copy&paste. Aber ich vermute das der eben tastatureingaben sendet. Aber das obere sieht ja schon eher so aus als ob es da auch ne schnittstelle gäbe mit der man sachen übergeben kann wie die URL.

Aber schon mal danke für die Rückmeldung.

**Comment by rols1** [comment]
Fire2kodi unterstützt bestimmte Addons: Youtube, Rumble, Odysee, Lbry, Bitchute, Dailymotion, Vimeo. Eine Anpassung der verwendeten Schnittstelle im ARDundZDF-Addon erscheint mir im Moment zu aufwendig. Ich schaue mir daher die zweite Variante näher an und teste die Umsetzung von Videolinks via Suchformular.

**Comment by carlos22** [comment]
Ok wobei das dann ja nicht über die normale share funktion gehen würde oder? Ich denke zumindest die anpassung im fire2kodi selbst wäre nicht so schwer. Wie das mit den Plugin parametern allerdings ist weiß ich nicht...

**Comment by rols1** [comment]
Ich hatte vor 2 Jahren [im Forum kodinerds eine ähnliche Anfrage](https://www.kodinerds.net/thread/64244-release-kodi-addon-ardundzdf/?postID=651334#post651334) - dort in umgekehrter Richtung. Das Addon sollte Downloadlinks an das Programm Jdownloader übergebe. Wie auch dort erwarte ich hier erheblichen Arbeits-/Zeit-Aufwand für eine Schnittstellenlösung. 
Bei der anderen Variante (kore, yatse o.ä "tippt" den Link in das Suchformular) entfällt die Schnittstelle. Das Addon muss sich dann "nur" noch um die Verarbeitung von Medienlinks kümmern.

**Comment by carlos22** [comment]
Ok verstehe, wobei das für mich jetzt nicht so schwer aussieht? Siehe: https://github.com/jaylinski/kodi-addon-vimeo/blob/0d1a3dddca744c3de95d7418b458b7aae38cd5a2/resources/plugin.py#L81
Also das wäre ja quasi die API wenn mach das so macht wie das fire2kodi das tut (und vermutlich ja auch kore bei ihm bekannten URLs wie youtube). 

Beim eintippen quasi über die UI tools würde man sich halt sparen das man selbst suchen muss also ein vorteil wäre es auf jeden fall, die handhabung wäre aber glaube ich etwas schwergängig weil man ja trotzdem copy&pasten muss und das share vermutlich nicht so einfach nutzen kann. Aber klar besser als suchen und dann nicht finden :)

**Comment by rols1** [comment]
Danke für den Link. Wenn ich es schon mundgerecht präsentiert bekomme, OK - ich schaue mir an, ob der Code sich für das ARDundZDF-Addon eignet. Bitte Geduld - das WE ist schon anderweitig verplant..

**Comment by carlos22** [comment]
Ja klar kein stress :) Ich werd die tage mal schauen ob ich das fire2kodi so angepasst bekomme das es für ard und zdf mediathek links funktioniert...
Das Kore macht es im übrigen sehr ähnlich und hat sogar support für ein arte plugin: https://github.com/xbmc/Kore/blob/a891d5f8da7fc6a783f07ce9b7038b0d82494a60/app/src/main/java/org/xbmc/kore/ShareOpenActivity.java#L268

Also ggf. könnte man dann da auch ein request / PR aufmachen und das sogar da integriert bekommen, das wäre natürlich ideal!

**Comment by rols1** [comment]
Hinsichtlich Übergabe von Medienlinks scheint auch [Yatse](https://yatse.tv/yatse-vs-kore) ein geeigneter Kandidat zu sein. Dort existiert ein [Api](https://yatse.tv/wiki/yatse-api), das auch einen selbst definierten Plugin-Url-Aufruf erlaubt:  `Action: "tv.yatse.api.PLAY_URI", "URI" [String]: The uri to play on media center (Can contains Media Center specific Uri like: "plugins://.....") `
Allerdings, nach dem Querlesen auch weiterer Quellen sehe ich: die Umsetzung einer Schnittstellenvariante ist jenseits meiner Möglichkeiten. 
Die Übernahme als sys.argv-Parameter in der Funktion router() des Addons und Weiterleitung zu einer Zielfunktion wäre dagegen wohl kein Problem. Z.B. könnte ein Medienlink via sys.argv[2] in der Form
`{'extern_medialink': 'https://www.3sat.de/preis-der-freiheit-3-100.html'}`
übergeben werden.
Eine Zielfunktion für die Auswertung von Medienlinks müsste zwar noch geschaffen werden, aber diesen Part halte ich für machbar. Bei einer ZDF-Video-Seite lassen sich im html-Text die Parameter entnehmen, die für die Ermittlung der Streams notwendigen Api-Call gebraucht werden. Bei den ARD-Links wie den im ersten Post genannten, handelt es sich um Base64-codierte crid-Urls, die direkt zu den Quellen führen können. Bei den Modulen (3sat, arte, audiothek, ..) ist möglicherweise mehr Kleinarbeit erforderlich.

Für den Request bedeutet das für mich zusammenfassend: um die Variante Übergabe via Schnittstellen muss sich jemand anderes kümmern. Ich beginne mit der Variante Suchformular (Übergabe von Medienlinks via Suchformular)  - mit gebotener Priorität für Weihnachten und Familie.

**Comment by rols1** [comment]
Bisher umgesetzt: Auswertung von Medienlinks im Suchformular für ARD.
Siehe akt. Beitrag im [Forum Kodinerds](https://www.kodinerds.net/thread/64244-release-kodi-addon-ardundzdf/?postID=768711#post770707).
Hinweise zu Einzelupdates siehe [Startpost Kodinerds](https://www.kodinerds.net/thread/64244-release-kodi-addon-ardundzdf/#post502022)

**Comment by rols1** [comment]
Berücksichtigung doppelt gesendeter Links (Yatse V11.7.5a) - Einzelupdate util.py

**Comment by carlos22** [comment]
Ah sehr cool.

> Allerdings, nach dem Querlesen auch weiterer Quellen sehe ich: die Umsetzung einer Schnittstellenvariante ist jenseits meiner Möglichkeiten.
> Die Übernahme als sys.argv-Parameter in der Funktion router() des Addons und Weiterleitung zu einer Zielfunktion wäre dagegen wohl kein Problem. Z.B. könnte ein Medienlink via sys.argv[2] in der Form

Aber ist nicht genau dieser Parameter im Grunde die Schnitstelle? Also so wie ich das sehe muss man da gar nichts tun ausser eben das sys.argv auswerten und kodi selbst parsed schon die pluginurl und fügt das da entsprechend ein? Das man das in Yatse frei konfiguieren kann ist natürlich super, damit könnte man das dann gut testen. Ich denke share to ist halt etwas intuitiver als das pasten über dialoge. 

Aber schon mal vielen Dank für die ganzen Mühen :)

**Comment by rols1** [comment]
[das Forum Kodinerds enthält den aktuellen Stand dazu..](https://www.kodinerds.net/thread/64244-release-kodi-addon-ardundzdf/?postID=771113#post771113)

**Comment by rols1** [comment]
ich würde den Request gerne als completed abschließen - einverstanden?. Die Wunschvariante (Link direkt teilen) konnte ich leider nicht erfüllen. Dagegen klappte es mit der im ersten Post angebotenen Alternative (Suche mit gescrapten Titel starten) besser als gedacht. Die aktuelle Umsetzung (Starten eines Medienlinks via Suchformular) führt sicherer zum Videostream als die Suche nach dem Titel einer Sendung.
Für die Wunschvariante habe ich im Addon eine einfache Schnittstelle geschaffen. Die Initiave zur Nutzung der Schnittstelle durch externe Programme, Apps, Scripts, o.ä. muss von den Nutzern dieser Programme ausgehen. Im gestern verlinkten Kodinerds-Post finden sich Hinweise, wie die Schnittstelle angesprochen werden kann, einschl. angehängtes Python-Script sowie ein Curl-Aufruf. 
**Achtung**: die Schnittstelle funktioniert bis zum nächsten regulären Update (Termin noch offen) nur mit dem [Testaddon auf gmx](https://c.gmx.net/@327723216099344844/cASZJUNuQpqlEImIS62dmA).

**Comment by carlos22** [comment]
Hallo ja klar auf jeden fall. Konnte es jetzt auch endlich testen funktioniert bisher super, ich bin begeistert! Vielen Dank. Ich werde jetzt mal versuchen das ganze auch in Kore zu bekommen.

**Comment by rols1** [comment]
Danke fürs Feedback. Zufällig habe ich bei den ARD-Streams noch ein abweichendes  Streamschema festgestellt, das nicht funktioniert. Falls es mit der Anpassung klapt, folgt ein reguläres Update am SO, 22.12.
