### ISSUE TITLE
Search in ARD yields a result count but no result page

### ISSUE THREAD

**Issue by monochromec** [rols1/Kodi-Addon-ARDundZDF#42]
To reproduce:

- Search for "Kurzschluss" 
- ARD will report 45 results
- But selecting these stays on the results page instead of displaying the results (as it does in the ZDF part)

Please let me know if additional info required - happy to help!

**Comment by rols1** [comment]
I can't reproduce this error. I tried the same search with Kodi Matrix and Leia (both Linux Mint) and Kodi Omega ( Raspi 3b+, LibreElec 12.0). I've changed the Settings "Inhaltstext zu Video im Voraus laden", "Ausschluss-Filter verwenden" and "Titel ganzer Sendungen markieren". However, the individual items are always displayed.
Please, could you upload a debug log?

**Comment by monochromec** [comment]
Can't reproduce this either. At some stage this pointed to a conversion issue in my previous PR but incorporating your modified PR in the addon CB the error seems to have gone. 

Closing this.
