### ISSUE TITLE
sorting rather incomprehensible

### ISSUE THREAD

**Issue by 2019-05-10** [rols1/Kodi-Addon-ARDundZDF#5]
Sorting is only asc or desc, but by what criterion is sorted, is not clear.
The obvious would be date, but that seems not to be the case nor the title.

Plausible criteria would be
- Date
- Length (I'll file a feature request with details)
- Title
- Channel

**Comment by rols1** [comment]
in this addon sorting options are only used in special cases. Main goal is to display content in the same order like on the website. I don't want to change this bevavior.
One special case for example is modul funk where sorting is used to match json outputs to web outputs (only in code, not as user-option).
/R

**Comment by rols1** [comment]
(teilweise) gelöst mit Update 4.1.2 vom 21.11.2021
/R
