### ISSUE TITLE
Installation klappt nicht

### ISSUE THREAD

**Issue by foss-** [rols1/Kodi-Addon-ARDundZDF#8]
https://github.com/rols1/Kodi-Addon-ARDundZDF#installation listet folgende Schritte:

INSTALLATION:

1. Download der zip-Datei: aktuelles Release, Leia-Version oder kodinerds-Repo, Leia- und Matrix-Version
2. Download script.module.kodi-six.zip hier https://github.com/romanvm/kodi.six/releases
3. Beide zip-Dateien mittels Kodi-Menü Addons/Addon-Browser installieren
4. Addon öffen und Addon-Einstellungen anpassen.
5. bebilderte Anleitung

Versucht mit Kodi 19.1 Matrix.
Download kodi.six 0.1.3.1 von https://github.com/romanvm/kodi.six/releases
Download Kodi-Addon-ARDundZDF 3.9.1 von https://github.com/rols1/Kodi-Addon-ARDundZDF/releases

Problem:
kodi.six konnte nicht installiert werden: `failed due to an invalid structure`
Kodi-Addon-ARDundZDF konnte nicht installiert werden: `The dependency on xbmc.python version 2.25.0 could not be satisfied.`

**Comment by rols1** [comment]
Hallo foss,
leider wurde es mit der Matrix-Version von Kodi unöglich, für die Erstinstallation die zip-Datei aus diesem Repo zu verwenden. Hierfür steht auf [kodinerds.net](https://repo.kodinerds.net) auch eine Matrix-Version des Addons zur Verfügung. Das vom Addon benötigte kodi-six-Modul wird bei der Installation autom. nachgeladen.
Falls bei den folgenden Updates der im Modul integrierte Updater verwendet wird (Menü Addon-Update), wird das Addon zwar auch von hier geladen, aber der Updater nimmt die für Matrix notwendige Anpassung vor. Das funktioniert, weil Kodi die Abhängigkeit der Python-Version im Addon nur beim Start von Kodi prüft, nicht aber wenn das Addon sich selbst updated.

Im Readme habe ich vorsichtshalber noch einen entsprechenden Hinweis in der Rubrik Installation eingefügt.
/R

**Comment by foss-** [comment]
Habe es nun mit `plugin.video.ardundzdf-3.9.1.zip` von https://repo.kodinerds.net/ versucht. Bei installation beschwert aber auch hier sich Kodi mit `The dependency on xbmc.python version 2.25.0 could not be satisfied.`

**Comment by rols1** [comment]
das war vermutlich die Krypton-(Leia-)-Versiondes Addons , die als erstes im Web gezeigt wird. Bitte im Tab Kodi-Version (oben links, neben Home) Kodi 19 auswählen.
Sollte das auch nicht klappen, bleibt noch die manuelle Anpassung der Datei addon.xml - erkläre ich bei Bedarf.
/R

**Comment by foss-** [comment]
Tatsache - das hat geklappt. Da Matrix die aktuelle Stable ist, würde es nicht sinnvoll, die Installationsschritte dafür auszulegen und ggf Schritte für ältere versionen hinter einem Zugeklappten Element zu verstecken? Idealierweise auch den Schritt für die Installation ergänzen im Readme?

**Comment by rols1** [comment]
guter Vorschlag. Bisher sah ich die Notwendigkeit noch nicht, da die Updatezahlen für die Leia-Version des Addons etwa doppelt so groß sind wie für Matrix. Aber wer z.Z. Kodi neu installiert, dürfte in der Tat Matrix verwenden.
Ich überlege mir eine passende Aktualisierung für das Readme.
Viel Spass mit dem Addon. Bitte für inhaltliche Hinweise (Fehler, Anregungen) das Forum [RELEASE-Kodi-Addon-ARDundZDF/](https://www.kodinerds.net/index.php/Thread/64244-RELEASE-Kodi-Addon-ARDundZDF/) nutzen.
/R
