### ISSUE TITLE
Download auf Samba-Share funktioniert nicht v3.9.1

### ISSUE THREAD

**Issue by nicro87** [rols1/Kodi-Addon-ARDundZDF#9]
Hallo,
erst einmal vielen Dank für dieses tolle Plugin. Es funktioniert als 1. Plugin einmal so, wie es soll :)

Jetzt zum Fehler:
Auf meinem Android-TV mit KODI Matrix (Addon Version 3.9.1) funktioniert der Download in ein (per Kodi) eingebundes Samba-Share leider nicht. Daher ist am TV der Download leider nicht nutzbar, da das Android TV natürlich nicht soviel Platz bietet.

Fehlermeldung:
test_downloads: Downloads nicht möglich
Downloadverzeichnis existiert nicht
Settings: smb://xxx:xxx@stor01/KODI/Downloads

Leider kann ich mir in dem Android TV auch nicht mit Symlink oder ähnlichem abhelfen. Ich gehe davon aus, dass Downloads nur in lokale Pfade unterstützt sind, richtig?

Vielen Dank und viele Grüße
Nico

**Comment by rols1** [comment]
Hallo,
in der Tat - Downloads sind nur in lokale Pfade möglich. Deshalb existiert ein Verschiebeverzeichnis - Setting "Download Einstellungen" / "Downloads verschieben in dieses Verzeichnis".
Siehe auch [Wicki Settings Download Zif.6](https://github.com/rols1/Kodi-Addon-ARDundZDF/wiki/3.-Settings-Download).
Grüße zurück..
/R

**Comment by nicro87** [comment]
Vielen Dank für die schnelle Antwort.
